import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test } from 'node:test';
import { generateProjectSkill, generateSkill, publishSkill } from '../dist/index.js';

const bytes = new TextEncoder().encode('{"openapi":"3.1.0","paths":{}}');

test('atomically migrates the same output between legacy and project generated trees', async () => {
  const output = await mkdtemp(join(tmpdir(), 'openapi-skill-publish-project-'));
  const legacy = generateSkill({ serviceId: 'legacy', skillName: 'api-docs', documents: new Map([['public', bytes]]) });
  const directory = await publishSkill(output, 'legacy', 'api-docs', legacy);
  assert.equal(JSON.parse(await readFile(join(directory, 'references', 'source.json'), 'utf8')).serviceId, 'legacy');

  const project = generateProjectSkill({ services: [
    { serviceId: 'orders', documents: new Map([['public', bytes]]) },
    { serviceId: 'shipping', sourceType: 'third-party', documents: new Map([['public', bytes]]) }
  ] });
  await publishSkill(output, 'api-docs', 'api-docs', project);
  assert.equal(JSON.parse(await readFile(join(directory, 'references', 'source.json'), 'utf8')).kind, 'project');

  await publishSkill(output, 'legacy', 'api-docs', legacy);
  assert.equal(JSON.parse(await readFile(join(directory, 'references', 'source.json'), 'utf8')).serviceId, 'legacy');
});

test('safely replaces an owned project generated by the former package identity', async () => {
  const output = await mkdtemp(join(tmpdir(), 'openapi-skill-publish-former-name-'));
  const previous = generateProjectSkill({ services: [
    { serviceId: 'orders', documents: new Map([['public', bytes]]) }
  ] });
  for (const [path, content] of previous) {
    const target = join(output, 'api-docs', ...path.split('/'));
    await mkdir(join(target, '..'), { recursive: true });
    await writeFile(target, content.replaceAll('openapi-skill-core/3', 'smartdoc-agent-core/3'));
  }

  const next = generateProjectSkill({ services: [
    { serviceId: 'orders', documents: new Map([['public', bytes]]) },
    { serviceId: 'shipping', documents: new Map([['public', bytes]]) }
  ] });
  const directory = await publishSkill(output, 'api-docs', 'api-docs', next);
  const source = JSON.parse(await readFile(join(directory, 'references', 'source.json'), 'utf8'));
  assert.equal(source.generatorVersion, 'openapi-skill-core/3');
  assert.deepEqual(source.services.map(({ serviceId }) => serviceId), ['orders', 'shipping']);
});

test('safely replaces an owned openapi-skill core/1 project with core/3', async () => {
  const output = await mkdtemp(join(tmpdir(), 'openapi-skill-publish-core1-'));
  const previous = generateProjectSkill({ services: [
    { serviceId: 'orders', documents: new Map([['public', bytes]]) }
  ] });
  for (const [path, content] of previous) {
    const target = join(output, 'api-docs', ...path.split('/'));
    await mkdir(join(target, '..'), { recursive: true });
    await writeFile(target, content.replaceAll('openapi-skill-core/3', 'openapi-skill-core/1'));
  }
  const next = generateProjectSkill({ services: [
    { serviceId: 'orders', documents: new Map([['public', bytes]]) },
    { serviceId: 'shipping', documents: new Map([['public', bytes]]) }
  ] });
  const directory = await publishSkill(output, 'api-docs', 'api-docs', next);
  const source = JSON.parse(await readFile(join(directory, 'references', 'source.json'), 'utf8'));
  assert.equal(source.generatorVersion, 'openapi-skill-core/3');
  assert.deepEqual(source.services.map(({ serviceId }) => serviceId), ['orders', 'shipping']);
});

test('removes a stale service when the complete project tree is replaced', async () => {
  const output = await mkdtemp(join(tmpdir(), 'openapi-skill-publish-removal-'));
  const complete = generateProjectSkill({ services: [
    { serviceId: 'orders', documents: new Map([['public', bytes]]) },
    { serviceId: 'shipping', documents: new Map([['public', bytes]]) }
  ] });
  const directory = await publishSkill(output, 'api-docs', 'api-docs', complete);
  const reduced = generateProjectSkill({ services: [{ serviceId: 'orders', documents: new Map([['public', bytes]]) }] });
  await publishSkill(output, 'api-docs', 'api-docs', reduced);
  const source = JSON.parse(await readFile(join(directory, 'references', 'source.json'), 'utf8'));
  assert.deepEqual(source.services.map(({ serviceId }) => serviceId), ['orders']);
  await assert.rejects(readFile(join(directory, 'references', 'services', 'shipping', 'references', 'source.json'), 'utf8'), /ENOENT/);
});

test('rejects inconsistent project provenance before writing output', async () => {
  const output = await mkdtemp(join(tmpdir(), 'openapi-skill-publish-invalid-project-'));
  const project = new Map(generateProjectSkill({ services: [
    { serviceId: 'orders', documents: new Map([['public', bytes]]) }
  ] }));
  const source = JSON.parse(project.get('references/source.json'));
  source.documents = [];
  project.set('references/source.json', JSON.stringify(source, null, 2));
  await assert.rejects(publishSkill(output, 'api-docs', 'api-docs', project), /flattened project documents/);
});

test('rejects an openapi-skill core/3 index that points to a missing contract', async () => {
  const output = await mkdtemp(join(tmpdir(), 'openapi-skill-publish-invalid-index-'));
  const operation = new TextEncoder().encode('{"openapi":"3.1.0","paths":{"/x":{"get":{"responses":{}}}}}');
  const files = new Map(generateSkill({
    serviceId: 'orders', skillName: 'orders-api', documents: new Map([['public', operation]])
  }));
  files.set('references/operations.jsonl', files.get('references/operations.jsonl')
    .replace('documents/public/operations/', 'documents/public/missing/'));
  await assert.rejects(publishSkill(output, 'orders', 'orders-api', files), /missing contract file/);
});
